### ISSUE TITLE
One access rule for multiple resources

### ISSUE THREAD

**Issue by ellie-narducci** [common-fate/glide#110]
DE = One access rule can be assigned to multiple resources simultaneously.
IO = Granted administrators can specify an org unit rather than individual accounts.
DE = If the access rule relates to an org unit, users can request which account they would like to request access to as part of their request form.
IO = Provider framework should support this methodology.

eg = In K8s allow users to choose a specific role they want access to.
eg = In AWS allow users can choose a specific account within an org unit they want access to. 

Imagine that you have 40 accounts and require 5 roles per account. That is 200 access rules which need to be created and maintained! This is very cumbersome and makes Granted a lot harder to manage. Even if we supported Terraform or YAML-based config for access rules, users might resort to “meta-templating” rules using Python or another scripting language to generate YAML. This makes Granted hard for a team to manage as it requires understanding a Python script which is generating config. This is based on the idea that one access rule grants access to one resource. 

My proposal to fix this is that we allow one access rule to grant access to multiple resources. e.g a user can select one or more AWS accounts and one or more Permission Sets when setting up the rule.

If a rule is configured with more than one account, a select field would appear in the new request page allowing the user to specify which account and permission set they are requesting access to.

This would make initial Granted Approvals deployments extremely easy and very powerful. With a single access rule, a team could allow any engineer in the company to request access to any AWS account with approval from the security team.

This would also make other providers like GitHub more powerful, e.g being able to request admin access to any repository rather than having to create access rules individually for each one.

This would make the new access request form take longer to fill out. To mitigate this, we could save the last few requests a user made and have some buttons at the top of the form called “recent requests” which would autofill the form data.

**Comment by JoshuaWilkes** [comment]
Notion spec here https://www.notion.so/commonfate/One-access-rule-for-multiple-targets-16cdc592a0df43d2849d25b724c71e6e
