### ISSUE TITLE
Improve experience for selecting a granted administrator group ID for SSO

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#115]
Once we have SSO config we can list groups via the API and use a survey.Select prompt to list the options, 

Ask if they want to update if its already set -> ask if they want to list options or enter an ID - prompt with options or accept ID
Then finally verify that the group exists before setting the config value and saving

The goal is to make it easier for an admin when they run gdeploy sso configure
At the end of this command flow, when they have connected their azure AD or okta SSO, the CLI prompts then to set the administrator Group ID.
This is what determines if a user is an admin.
Once SSO is configured, use the listGroups method of the identityprovider and display the options using a survey.Select prompt if the users chooses to else, allow them to enter an id directly.
DE = before prompting to list all groups, ask the user if they want to enter an id or select from a list of their groups. so you can just enter it if you already have it
DE = if they want to list, they should be able to search the groups by name. if possible, show the description too if we have that information?
DE = if they enter a group id directly, validate that the group exists. You can implement this as a validator on the survey.Input prompt so they get promopted to re enter the id if it does not exist.

**Comment by chrnorm** [comment]
@JoshuaWilkes I'm assuming this is for `gdeploy` right?

**Comment by JoshuaWilkes** [comment]
Correct

**Comment by jordiup** [comment]
Checking out this one now, playing around with the aws SDK to fetch a list sso instances response. Will continue next week

**Comment by chrnorm** [comment]
@jordiup you’ll need to work with Josh to clarify the tasking here - this is for the SSO connection in gdeploy (Azure AD, Okta or Google) rather than the AWS SSO provider. The naming is confusing here!
