### ISSUE TITLE
EKS: add access instructions

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#128]
Done = Access Instructions allow users to copy/paste some commands to run in their terminal which configures their local kubeconfig file so they can access the cluster.

DE = As a user I can run commands I've pasted from Granted Approvals and then start working on the cluster immediately.

**Comment by meyerjrr** [comment]
~~Where are we wanting these instructions? Currently the draft docs have reference to the following command which updates local kubectl config to know about a cluster~~
```
aws eks update-kubeconfig --name {CLUSTER_NAME}
```
~~Do we want to add this as a prompt to the cli?~~

Edit: Ran through the DE with Josh
