### ISSUE TITLE
EKS: limit the permissions that Granted needs within the cluster

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#132]
Done = Granted should only have access to modify the `aws-auth` ConfigMap, nothing else

**Comment by JoshuaWilkes** [comment]
@chrnorm granted needs to add rolemappings to a user for teh aws-auth to point to

**Comment by JoshuaWilkes** [comment]
The unfortunate issue here also @chrnorm is that kubernetes is protected from privilege escalation. 
What this means is that the access handler role needs to have equal or higher permissions than the roles it assigns to users. 

Also, the clusterrole assumed by the access handler is configured by the Admin when setting up the provider. So they are in control of the access level. but it needs to be at least as much access as the roles it is assigning to users.

An option here may be that we define the policy needed to carry out teh role mapping. Then we get the admins to add a rolemapping for each role they want to use granted with, to the access handler management role. then its guaranteed to only have the access that it needs to have to run correctly.

We can probably setup the list roles operation to only return the roles that are mapped to the management user
