### ISSUE TITLE
Pull CloudTrail logs for the Access Role and associate them with the Access Request

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#158]
This is a task that can be completed after the initial provider is implemented.

DE = it should be possible to deploy the flask shell provider **without** configuring CloudTrail access. Users should be able to connect their CloudTrail as a second step after they've deployed the initial provider. This is because CloudTrail and Athena are a pain to set up, especially if they have an existing CloudTrail Data Lake somewhere in their org. Granted will need to assume a cross-account role in order to access this.

DE = admins can see which command was run in the Docker container to verify that it was the `flask shell` command.

Granted needs to pull CloudTrail logs relating to the access request and create audit trail events associated with them, exactly the same as our flask shell logs.

We need to use a 'pull' approach rather than a 'push' approach here ("push" approach = flask shell sending logs to the Granted webhook).

[Related internal wiki doc on ECS logs with some example CloudTrail events](https://www.notion.so/commonfate/Auditing-ECS-shell-access-57c0990793204ad7a985b218e003beab)

IO = ECS logs are pulled as quickly as possible 

Done = CloudTrail ECS Exec event appears as an audit trail event associated with the Access Request.

**Comment by JoshuaWilkes** [comment]
Pulling logs is simple
Pulling them often enough is a challenge
We don't want to pull logs unless we have active or recently active requests
We should pull logs while a loggable request is active and some time after it expires

Wan't to avoid running queries unless we need to as they cost money 💵 


- work out the cadence and conditions for running a query
- work out what triggers it if any
- queries can take a long time to run, watch out for lambda exectution timeout
-
