### ISSUE TITLE
Make `gdeploy init` more user friendly

### ISSUE THREAD

**Issue by ellie-narducci** [common-fate/glide#163]
Currently `gdeploy init` is not user friendly.
```
❯ gdeploy init
[✘] Failed to load AWS credentials.
Please export valid AWS credentials to run this command.
```

When a user runs into an error we should make it more self-guided and work without the user needing to refer to the docs.

This command should be self-documenting and should help the user log in to AWS using similar logic to assume.

At the very least we should ask for a profile the user wants to use and then try and load it.

**Comment by ellie-narducci** [comment]
There's not a whole heap of spec here but keen for whoever picks this up to own it and spec it up as they see fit!

**Comment by jordiup** [comment]
Actions taken as a part of this ticket



- [x] Audit instances of `clio.NewCLIError` 
These are the methods responsible for `[✘] Failed to load AWS credentials.`. Besides the AWS Credential errors, error messages provide ample context, explanation, recommended next steps
The AWS Credential errors aren't very suggestive (no next-steps). To remedy this I've added a section to docs
https://github.com/common-fate/docs/pull/76
And the corresponding link in the CLI
https://github.com/common-fate/granted-approvals/pull/170


- [x] Run through a fresh install using `gdeploy` 
I'm pretty happy with how the whole install process went, whole stack deployed in under 10 minutes

Based on these actions I think we can cover off this ticket, open to further thoughts/review 👌
