### ISSUE TITLE
The `commonfate/aws-sso` provider shouldn't allow access rules to be created which point to the management account

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#175]
Related to #174 - if the `aws-sso` provider is running in a delegated admin account and doesn't assume a role in the main account, we shouldn't include the main account in the argument options for the provider.

IO = check the organization root account ID and compare the role ARN to it - if they don't match, don't include the main account in the list of options

**Comment by JoshuaWilkes** [comment]
@chrnorm should we just cancel this and move forward with the alternative sso provider?
