### ISSUE TITLE
Pass in real TemplateData to the provider setup instructions

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#192]
TemplateData is a config struct which is used to provide placeholders in the setup instructions for access providers. Currently we use it to replace instructions with the actual role ARN that the Access Handler is running as.

Currently when setting up the Approvals API we initialise a placeholder value for the `TemplateData`. This data is:
```
TemplateData: psetup.TemplateData{
				AccessHandlerRoleARN: "arn:aws:iam:123456789012:role/access-handler-role",
			},
```

We need to replace this TemplateData with the actual role ARN.

The challenge here is that we have a couple of different Lambdas which run, each with their own role. I think the solution here is that we need to introduce a new `AccessHandlerRole` role with a trust relationship which allows both the Access Handler API, and the Granter lambdas to assume it. From there, we can use this role to build trust relationships to roles in other accounts.

**Comment by JoshuaWilkes** [comment]
We have just been make the trust relation with both the granter and access handler rest api roles.

I have plumbed these through for now, I will look at the assumed role option, 
I anticipate some annoyance for dev with assumed role, specifically when running locally, though we could skip the assume role in dev using some config

**Comment by JoshuaWilkes** [comment]
I have been working on this and hopefully will be able to shift to a single access handler role for the purpose of these templates/assume role for providers
