### ISSUE TITLE
Granted Approvals doesn't support IDP-initiated SAML SSO

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#215]
When Granted Approvals is connected to an IDP like Okta, clicking the sign-in button in Okta causes an error to be displayed in the Approvals UI.

**Comment by chrnorm** [comment]
Taking a look now into the IDP-initiated flow now - frustratingly, Amazon Cognito has a limitation where IDP-initiated SAML flows don’t work.

In the meantime, there is a workaround available to get a shortcut to Granted Approvals on team members’ Okta dashboards.

1. Enable the “Do not display application icon to users” setting in the Granted Approvals SAML application (see screenshot).
2. Create a Bookmark App following Okta’s guide [here](https://support.okta.com/help/s/article/How-do-you-create-a-bookmark-app?language=en_US). The URL it points to should be your Granted deployment URL.
3. Assign the Bookmark App to the same groups that the Granted Approvals SAML app is assigned to.
Note that you can also add an icon to the Bookmark App so the app is more distinguishable to users.

The task here is to add this limitation and workaround to our setup documentation https://docs.commonfate.io.

**Comment by jordiup** [comment]
PR for docs
https://github.com/common-fate/docs/pull/84
