### ISSUE TITLE
v0.4.0 acceptance testing

### ISSUE THREAD

**Issue by chrnorm** [common-fate/glide#218]
Tracking issue for things I've found in acceptance testing of our next upcoming release.

- [x] Admins should be taken directly to an onboarding page to set up their first provider, rather than being directed to our docs.
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/17420369/187957169-28ca14f5-bbbd-4615-a492-a297e9ca7b87.png">

- [x] instructions for creating an IAM role need to be made a bit clearer.
  - we need to indicate that the IAM role should be created in the management account.
  - the role provisioning should be done via CloudFormation. The instructions for creating the IAM role should be along these lines:
    - Copy the following YAML and save it as 'granted-sso-role.yml'
    - -YAML CloudFormation file contents-
    - Open the AWS Console in your organisation's management account and click 'create stack'
    - -Screenshots of the CloudFormation console-
    - Upload the template file
    - Name the stack 'Granted-SSO-Role'
    - Deploy the stack
    - Copy the "RoleARN" output from the stack and paste it in the *ssoRoleArn* config value on the right.

- [x] assume role check needs to actually run in V2 AWS SSO provider! and be removed from v1 provider. When running the provider tests
- [x] remove “Alternatively, you can view the YAML configuration
 to set up the provider.” text → needs to be ticketed to be added in a future release

- [x] remove the question mark icon from here (it was intended to be used for some help text in case users weren't familiar with the YAML-based config approach we use, needs to be added in a future release)
<img width="682" alt="image" src="https://user-images.githubusercontent.com/17420369/187959424-1dc6e36e-5f20-4a09-813a-0da527dc9ad1.png">

- [x] fix “Access will be activated immediately after approval” appearing everywhere
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/17420369/187959666-5d4e2f33-dde1-404f-8417-41592c60ca2a.png">

- [x] improve UI here - “Target Selections” is a bit jargon-ey and should be removed. Additionally formatting/font size makes it difficult to read/separate the labels from the values.
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/17420369/187959846-69f9cee3-ed20-46a7-aa66-1466a9e9fc1e.png">

- [x] fix Okta instructions formatting 
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/17420369/187959888-3d3a1290-50c6-4999-bf2d-7685e2ad6bcf.png">

- [x] fix Azure AD instructions formatting

<img width="806" alt="image" src="https://user-images.githubusercontent.com/17420369/187959976-f16f085f-e432-4edf-917a-fa0229ef7ce4.png">

- [x] Azure AD groups validation doesn't work, preventing the setup flow from continuing
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/17420369/187960105-e8eefb33-ff26-4efa-b601-88a4add459d2.png">

**Comment by JoshuaWilkes** [comment]
We should improve the UI here for selectable fields on the request access rule form for an end user
ideally, 

- [ ] use the field Title from the provider arg schema instead of the ID for the field
- [ ] Add some information so the use knows what / why to select options
<img width="948" alt="image" src="https://user-images.githubusercontent.com/14214200/188036903-bee7d8c7-132a-4ea5-bc81-a9c8d83fd5ad.png">

**Comment by JoshuaWilkes** [comment]
Updates for request details

<img width="704" alt="image" src="https://user-images.githubusercontent.com/14214200/188042756-455da077-c44f-4791-b341-77dfa9b586a0.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/14214200/188042789-e2481b6b-50dd-4265-bf92-5d1e5e200085.png">
